import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import SideBar from "./Components/SideBar";
import { SearchProvider } from "./Components/SearchContext";
import Headers from './Components/Header'
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SearchProvider>
      <html lang="en">
        <body
          className="py-0" 
        >
          <Headers/>
          <div className="flex">
          <SideBar/>
          {children}
          </div>
        </body>
      </html>
    </SearchProvider>
  );
}
